openapi: 3.0.0
info:
  x-skaffolder-id-project: 5e31b4098b307f16078dd1cd
  title: example
  description: You can obtain JWT token from login API
  version: 0.1
servers:
  - url: http://localhost:3000/api
    description: Local server for testing
paths:
  /login:
    post:
      x-skaffolder-ignore: true
      summary: Login API
      security: []   # No security
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:   # Sample object
                username: admin
                password: 62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /verifyToken:
    post:
      x-skaffolder-ignore: true
      summary: Verify token API
      security: [] #No security
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /changePassword:
    post:
      x-skaffolder-ignore: true
      summary: Change password API
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                passwordNew:
                  type: string
                passwordOld:
                  type: string
      responses:
        '200':
          description: OK
                

  #-----  Address  -----
  #-----  Posts  -----
  /posts/:
    post:
      x-skaffolder-id: 5e31be248b307f16078dd388
      x-skaffolder-name: create
      x-skaffolder-id-resource: 5e31b9bf8b307f16078dd2ee
      x-skaffolder-resource: Posts
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - Posts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Posts"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                image:
                  type: string
                name:
                  type: string
    get:
      x-skaffolder-id: 5e31be248b307f16078dd38b
      x-skaffolder-name: list
      x-skaffolder-id-resource: 5e31b9bf8b307f16078dd2ee
      x-skaffolder-resource: Posts
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - Posts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Posts"
    
  /posts/{id}:
    delete:
      x-skaffolder-id: 5e31be248b307f16078dd38c
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 5e31b9bf8b307f16078dd2ee
      x-skaffolder-resource: Posts
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - Posts
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 5e31be248b307f16078dd387
      x-skaffolder-name: get
      x-skaffolder-id-resource: 5e31b9bf8b307f16078dd2ee
      x-skaffolder-resource: Posts
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - Posts
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Posts"
    post:
      x-skaffolder-id: 5e31be248b307f16078dd385
      x-skaffolder-name: update
      x-skaffolder-id-resource: 5e31b9bf8b307f16078dd2ee
      x-skaffolder-resource: Posts
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - Posts
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Posts"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Posts"
    
  #-----  User  -----
  /user/{id}/changePassword:
    post:
      x-skaffolder-id: 5e31b40a8b307f16078dd1e2
      x-skaffolder-name: changePassword
      x-skaffolder-id-resource: 5e31b4098b307f16078dd1d7
      x-skaffolder-resource: User
      x-skaffolder-crudAction: 
      x-skaffolder-crudType: 
      x-skaffolder-description: Change password of user from admin
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: object
      x-skaffolder-url: /{id}/changePassword
      x-skaffolder-roles: ["ADMIN"]
      summary: Change password of user from admin
      tags:
        - User
      responses:
        "200":
          description: OK
    
  /user/:
    post:
      x-skaffolder-id: 5e31b40a8b307f16078dd1e1
      x-skaffolder-name: create
      x-skaffolder-id-resource: 5e31b4098b307f16078dd1d7
      x-skaffolder-resource: User
      x-skaffolder-crudAction: create
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION create
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION create
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
                name:
                  type: string
                password:
                  type: string
                roles:
                  type: string
                surname:
                  type: string
                username:
                  type: string
    get:
      x-skaffolder-id: 5e31b40a8b307f16078dd1db
      x-skaffolder-name: list
      x-skaffolder-id-resource: 5e31b4098b307f16078dd1d7
      x-skaffolder-resource: User
      x-skaffolder-crudAction: list
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION list
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /
      x-skaffolder-roles: []
      summary: CRUD ACTION list
      tags:
        - User
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    
  /user/{id}:
    delete:
      x-skaffolder-id: 5e31b40a8b307f16078dd1da
      x-skaffolder-name: delete
      x-skaffolder-id-resource: 5e31b4098b307f16078dd1d7
      x-skaffolder-resource: User
      x-skaffolder-crudAction: delete
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION delete
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION delete
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    get:
      x-skaffolder-id: 5e31b40a8b307f16078dd1df
      x-skaffolder-name: get
      x-skaffolder-id-resource: 5e31b4098b307f16078dd1d7
      x-skaffolder-resource: User
      x-skaffolder-crudAction: get
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION get
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION get
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    post:
      x-skaffolder-id: 5e31b40a8b307f16078dd1dc
      x-skaffolder-name: update
      x-skaffolder-id-resource: 5e31b4098b307f16078dd1d7
      x-skaffolder-resource: User
      x-skaffolder-crudAction: update
      x-skaffolder-crudType: 
      x-skaffolder-description: CRUD ACTION update
      x-skaffolder-returnDesc: 
      x-skaffolder-returnType: 
      x-skaffolder-url: /{id}
      x-skaffolder-roles: []
      summary: CRUD ACTION update
      tags:
        - User
      parameters:
        - name: id
          x-skaffolder-type: ObjectId
          in: path
          description: Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
    
    
# JWT security
security:
  - bearerAuth: [] 
  
  
# Components
components:

  # Security
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes

  # Data Model
  schemas:
        

    Address:
      x-skaffolder-id: 5e33344c0e3805651222d40b
      x-skaffolder-id-db: 5e31b4098b307f16078dd1ce
      x-skaffolder-id-entity: 5e33344c0e3805651222d408
      x-skaffolder-url: /address
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        address:
          type: string
          x-skaffolder-id-attr: 5e33344c0e3805651222d409
          x-skaffolder-type: String
          x-skaffolder-required: true
      x-skaffolder-relations: 
        user_id:
          x-skaffolder-type: 1:m
          x-skaffolder-ent1: 5e33344c0e3805651222d408
          x-skaffolder-ent2: 5e31b4098b307f16078dd1cf
      required:
        - _id
        - address
      
    
    Posts:
      x-skaffolder-id: 5e31b9bf8b307f16078dd2ee
      x-skaffolder-id-db: 5e31b4098b307f16078dd1ce
      x-skaffolder-id-entity: 5e31b9bf8b307f16078dd2ea
      x-skaffolder-url: /posts
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        description:
          type: string
          x-skaffolder-id-attr: 5e31b9bf8b307f16078dd2ed
          x-skaffolder-type: String
          x-skaffolder-required: true
        image:
          type: string
          x-skaffolder-id-attr: 5e31b9bf8b307f16078dd2ec
          x-skaffolder-type: String
          x-skaffolder-required: true
        name:
          type: string
          x-skaffolder-id-attr: 5e31b9bf8b307f16078dd2eb
          x-skaffolder-type: String
          x-skaffolder-required: true
      x-skaffolder-relations: 
        id_user:
          x-skaffolder-type: 1:m
          x-skaffolder-ent1: 5e31b9bf8b307f16078dd2ea
          x-skaffolder-ent2: 5e31b4098b307f16078dd1cf
      required:
        - _id
        - description
        - image
        - name
      
    
    User:
      x-skaffolder-id: 5e31b4098b307f16078dd1d7
      x-skaffolder-id-db: 5e31b4098b307f16078dd1ce
      x-skaffolder-id-entity: 5e31b4098b307f16078dd1cf
      x-skaffolder-url: /user
      properties:
        _id:
          type: string
          x-skaffolder-required: true
        mail:
          type: string
          x-skaffolder-id-attr: 5e31b4098b307f16078dd1d2
          x-skaffolder-type: String
        name:
          type: string
          x-skaffolder-id-attr: 5e31b4098b307f16078dd1d3
          x-skaffolder-type: String
        password:
          type: string
          x-skaffolder-id-attr: 5e31b4098b307f16078dd1d1
          x-skaffolder-type: String
          x-skaffolder-required: true
        roles:
          type: string
          x-skaffolder-id-attr: 5e31b4098b307f16078dd1d5
          x-skaffolder-type: String
        surname:
          type: string
          x-skaffolder-id-attr: 5e31b4098b307f16078dd1d4
          x-skaffolder-type: String
        username:
          type: string
          x-skaffolder-id-attr: 5e31b4098b307f16078dd1d0
          x-skaffolder-type: String
          x-skaffolder-required: true
      x-skaffolder-relations: 
      required:
        - _id
        - password
        - username
      
    
    
  # Databases
  x-skaffolder-db:
    - x-skaffolder-id: 5e31b4098b307f16078dd1ce
      x-skaffolder-name: labo_db

  # Pages
  x-skaffolder-page:
    - x-skaffolder-id: 5e31b4098b307f16078dd1d6
      x-skaffolder-name: Home
      x-skaffolder-url: /home
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
        - 5e31be248b307f16078dd38a
      x-skaffolder-roles: []
    - x-skaffolder-id: 5e31bd618b307f16078dd37c
      x-skaffolder-name: Posts
      x-skaffolder-url: /posts
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
      x-skaffolder-roles: []
    - x-skaffolder-id: 5e31be248b307f16078dd384
      x-skaffolder-name: PostsEdit
      x-skaffolder-url: /postses/{id}
      x-skaffolder-template: Edit_Crud
      x-skaffolder-resource: 5e31b9bf8b307f16078dd2ee
      x-skaffolder-services: 
        - 5e31be248b307f16078dd388
        - 5e31be248b307f16078dd387
        - 5e31b40a8b307f16078dd1db
        - 5e31be248b307f16078dd385
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
      x-skaffolder-roles: []
    - x-skaffolder-id: 5e31be248b307f16078dd38a
      x-skaffolder-name: PostsList
      x-skaffolder-url: /postses
      x-skaffolder-template: List_Crud
      x-skaffolder-resource: 5e31b9bf8b307f16078dd2ee
      x-skaffolder-services: 
        - 5e31be248b307f16078dd38c
        - 5e31be248b307f16078dd38b
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
        - 5e31be248b307f16078dd384
      x-skaffolder-roles: []
    - x-skaffolder-id: 5e31bd398b307f16078dd37a
      x-skaffolder-name: Products
      x-skaffolder-url: /products
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
      x-skaffolder-links: 
      x-skaffolder-roles: []
    - x-skaffolder-id: 5e31bd718b307f16078dd380
      x-skaffolder-name: Profile
      x-skaffolder-url: /profile
      x-skaffolder-template: 
      x-skaffolder-resource: 
      x-skaffolder-services: 
      x-skaffolder-nesteds: 
        - 5e31bd618b307f16078dd37c
        - 5e31bd398b307f16078dd37a
      x-skaffolder-links: 
      x-skaffolder-roles: []
